version: "3.8"

services:
  mongodb:
    image: mongo:6
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db

  backend:
    # build: ./backend
    image: tranhieuphuc12/my-journal-be:latest
    container_name: backend_container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/mydatabase

  frontend:
    # build: ./frontend
    image: tranhieuphuc12/my-journal-fe:latest
    container_name: frontend_container
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - backend